DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS AUDIT_LOG;

CREATE TABLE accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    balance DOUBLE
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    FROM_ACCOUNT INT,
    TO_ACCOUNT INT,
    AMOUNT DOUBLE,
    STATUS VARCHAR(20),
    CREATED_TIME TIMESTAMP
);

CREATE TABLE AUDIT_LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    ACTION VARCHAR(100),
    USER_ID INT,
    CREATED_TIME TIMESTAMP
);

INSERT INTO accounts (ID, OWNER_NAME, BALANCE) VALUES (1, 'Alice', 1000);
INSERT INTO accounts (ID, OWNER_NAME, BALANCE) VALUES (2, 'Bob', 500);