spring.application.name=bankdemo

#spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8081
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.h2.console.settings.web-allow-others=true
spring.sql.init.mode=never

spring.jpa.properties.hibernate.format_sql=true


# Dùng H2 in-memory database
#spring.datasource.url=jdbc:h2:mem:testdb#
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create   # t?o b?ng t? ??ng
#spring.h2.console.enabled=true         # m? console H2
#spring.h2.console.path=/h2-console     # ???ng d?n console
#spring.jpa.show-sql=true               # hi?n th? SQL ra console