DELETE FROM TRANSACTIONS;
DELETE FROM AUDIT_LOG;
DELETE FROM ACCOUNT;

INSERT INTO ACCOUNT (ID, OWNER_NAME, BALANCE)
VALUES (1,'Alice',1000);

INSERT INTO ACCOUNT (ID, OWNER_NAME, BALANCE)
VALUES (2,'Bob',500);